In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('covid_toy.csv')

In [3]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid'],axis=1),
                                                df['has_covid'],
                                                test_size=0.2)

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder

In [8]:
transformer = ColumnTransformer(transformers=[
    ('trf1',SimpleImputer(),['fever']),
    ('trf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('trf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [15]:
x_train_transformer = transformer.fit_transform(x_train)

In [18]:

x_train_transformer

array([[100.8028169,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  84.       ],
       [ 99.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  59.       ],
       [102.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          1.       ,  74.       ],
       [ 99.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  72.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  83.       ],
       [ 99.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  49.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  71.       ],
       [102.       ,   1.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  20.       ],
       [ 99.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  22.       ],
       [ 99.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  66.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  20.       ],
       [100.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  27.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  38.       ],
       [ 98.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  73.       ],
       [100.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  27.       ],
       [101.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  14.       ],
       [ 98.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  80.       ],
       [100.8028169,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  38.       ],
       [ 99.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  25.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  81.       ],
       [101.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  49.       ],
       [103.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  73.       ],
       [100.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  27.       ],
       [102.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  49.       ],
       [104.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   6.       ],
       [102.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  82.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  51.       ],
       [104.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  75.       ],
       [104.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  12.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   5.       ],
       [101.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  68.       ],
       [100.8028169,   1.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  71.       ],
       [ 99.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  14.       ],
       [ 99.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  60.       ],
       [100.8028169,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  75.       ],
       [ 98.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  31.       ],
       [104.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  54.       ],
       [102.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  33.       ],
       [100.8028169,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  20.       ],
       [101.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  42.       ],
       [103.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  60.       ],
       [100.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  11.       ],
       [100.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  19.       ],
       [100.8028169,   1.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  79.       ],
       [103.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  83.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  11.       ],
       [103.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  48.       ],
       [ 99.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  65.       ],
       [102.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  82.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  13.       ],
       [102.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   5.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  25.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  65.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   8.       ],
       [103.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  50.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  10.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  19.       ],
       [103.       ,   1.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  70.       ],
       [100.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  55.       ],
       [101.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  19.       ],
       [101.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  47.       ],
       [ 98.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  40.       ],
       [102.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  24.       ],
       [ 98.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          1.       ,  23.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  19.       ],
       [ 98.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  24.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  47.       ],
       [100.8028169,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  42.       ],
       [ 98.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  83.       ],
       [103.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  46.       ],
       [102.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  69.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          1.       ,  42.       ],
       [100.8028169,   0.       ,   1.       ,   0.       ,   0.       ,
          1.       ,  23.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          1.       ,  44.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  16.       ],
       [100.8028169,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  34.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  69.       ],
       [101.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  15.       ],
       [100.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  80.       ],
       [102.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  64.       ]])

In [21]:
column_names = transformer.get_feature_names_out()
x_train_df = pd.DataFrame(x_train_transformer,columns=column_names)

In [22]:
x_train_df

,trf1__fever,trf2__cough,trf3__gender_Male,trf3__city_Delhi,trf3__city_Kolkata,trf3__city_Mumbai,remainder__age
0,100.802817,0.0,0.0,0.0,0.0,0.0,84.0
1,99.000000,1.0,0.0,1.0,0.0,0.0,59.0
2,102.000000,0.0,1.0,0.0,0.0,1.0,74.0
3,99.000000,0.0,1.0,0.0,0.0,0.0,72.0
4,101.000000,0.0,0.0,0.0,1.0,0.0,83.0
...,...,...,...,...,...,...,...
75,100.802817,1.0,0.0,0.0,0.0,1.0,34.0
76,98.000000,1.0,0.0,0.0,0.0,1.0,69.0
77,101.000000,0.0,1.0,1.0,0.0,0.0,15.0
78,100.000000,0.0,1.0,0.0,0.0,0.0,80.0
79,102.000000,0.0,1.0,0.0,0.0,0.0,64.0