In [1]:
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer

In [3]:
df = pd.read_csv('train.csv')[['Age','Fare','SibSp','Parch','Survived']]

In [4]:
df.isnull().sum()

Age         177
Fare          0
SibSp         0
Parch         0
Survived      0
dtype: int64

In [5]:
df['family'] = df['SibSp'] + df['Parch']

In [6]:
df.head()

    Age     Fare  SibSp  Parch  Survived  family
0  22.0   7.2500      1      0         0       1
1  38.0  71.2833      1      0         1       1
2  26.0   7.9250      0      0         1       0
3  35.0  53.1000      1      0         1       1
4  35.0   8.0500      0      0         0       0

In [7]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [8]:
df.head()

    Age     Fare  Survived  family
0  22.0   7.2500         0       1
1  38.0  71.2833         1       1
2  26.0   7.9250         1       0
3  35.0  53.1000         1       1
4  35.0   8.0500         0       0

In [9]:
x = df.drop(columns=['Survived'])
y = df['Survived']

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [11]:
from sklearn.preprocessing import Binarizer

In [12]:
trf = ColumnTransformer([
    ('bin',Binarizer(copy=False),['family'])
],remainder='passthrough')

In [13]:
x_train_trf = trf.fit_transform(x_train)
x_test_trf = trf.transform(x_test)

In [14]:
x_train_trf

array([[  0.    ,  45.5   ,  28.5   ],
       [  0.    ,  23.    ,  13.    ],
       [  0.    ,  32.    ,   7.925 ],
       ...,
       [  1.    ,  41.    ,  14.1083],
       [  1.    ,  14.    , 120.    ],
       [  1.    ,  21.    ,  77.2875]])

In [16]:
pd.DataFrame(x_train_trf,columns=['family','Age','Fare'])

     family   Age      Fare
0       0.0  45.5   28.5000
1       0.0  23.0   13.0000
2       0.0  32.0    7.9250
3       1.0  26.0    7.8542
4       1.0   6.0   31.2750
..      ...   ...       ...
707     0.0  21.0    7.6500
708     0.0   NaN   31.0000
709     1.0  41.0   14.1083
710     1.0  14.0  120.0000
711     1.0  21.0   77.2875

[712 rows x 3 columns]

In [17]:
clf = DecisionTreeClassifier()
clf.fit(x_train_trf,y_train)
y_pred = clf.predict(x_test_trf)

accuracy_score(y_test,y_pred)

0.6312849162011173

Here before doing binarization my accracy was 61% but with applying this technique the accracy is increased.